MODEL:
  TYPE: swin_multi_exit
  NAME: swin_base_patch4_window7_224
  DROP_PATH_RATE: 0.5
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    EXIT_LIST: [6, 8, 10, 12, 14, 16, 18, 20]
    WINDOW_SIZE: 7