MODEL:
  TYPE: swin_multi_exit
  NAME: multi_exit
  DROP_PATH_RATE: 0.5
  LOSS_TYPE: multi_exit_loss
  EXIT_CHECK: 8
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    EXIT_LIST: [6, 8, 10, 12, 14, 16, 18, 20]
    WINDOW_SIZE: 7